@BASE_URL = http://localhost:3000/api

GET {{BASE_URL}}/users
###

GET {{BASE_URL}}/users/5ef96116d21a1f2af9ef2545
###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name":"jimmy",
    "userName":"jimmy",
    "email":"jimmy@gmail.com",
    "password":"jimmy"
}

###
PATCH {{BASE_URL}}/users/5efa3d9c336dc931e00c3c22
Content-Type: application/json

{
    "password":"12344321"
}

###
DELETE {{BASE_URL}}/users/5ef979f04352933be5f1e14b
Content-Type: application/json


# POST {{BASE_URL}}
# Content-Type: application/x-www-form-urlencoded

# name=Orhan&surname=SALUR&age&32

###
POST {{BASE_URL}}/users/login
Content-Type: application/json

{
    "email":"jimmy@gmail.com",
    "password":"12344321"
}