@BASE_URL = http://localhost:3000/api

GET {{BASE_URL}}/users
###

GET {{BASE_URL}}/users/5ef96116d21a1f2af9ef2545
###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name":"test",
    "userName":"test1",
    "email":"test1@gmail.com",
    "password":"12344321"
}

###
PATCH {{BASE_URL}}/users/5ef96116d21a1f2af9ef2545
Content-Type: application/json

{
    "name":"jimmy",
    "userName":"jimmy",
    "email":"jimmy@gmail.com"
}

###
DELETE {{BASE_URL}}/users/d
Content-Type: application/json


# POST {{BASE_URL}}
# Content-Type: application/x-www-form-urlencoded

# name=Orhan&surname=SALUR&age&32